// <auto-generated />
namespace LocationVoiture.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeId_blackList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeId_blackList));
        
        string IMigrationMetadata.Id
        {
            get { return "202102062315134_changeId_blackList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
