// <auto-generated />
namespace LocationVoiture.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addBlockUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addBlockUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202102111151506_addBlockUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
