// <auto-generated />
namespace LocationVoiture.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addBlackList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addBlackList));
        
        string IMigrationMetadata.Id
        {
            get { return "202102062241449_addBlackList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
