//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationVoiture.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocationVoiture.Resources.Views.Shared.Dashboard", typeof(Dashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black list.
        /// </summary>
        public static string black_list {
            get {
                return ResourceManager.GetString("black_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string car {
            get {
                return ResourceManager.GetString("car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favotite list.
        /// </summary>
        public static string favorite_list {
            get {
                return ResourceManager.GetString("favorite_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string loc {
            get {
                return ResourceManager.GetString("loc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string locataire {
            get {
                return ResourceManager.GetString("locataire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string nb {
            get {
                return ResourceManager.GetString("nb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number total of client register.
        /// </summary>
        public static string nb_client {
            get {
                return ResourceManager.GetString("nb_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Tenant.
        /// </summary>
        public static string nb_loc {
            get {
                return ResourceManager.GetString("nb_loc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reservations.
        /// </summary>
        public static string nb_res {
            get {
                return ResourceManager.GetString("nb_res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cars.
        /// </summary>
        public static string nb_voi {
            get {
                return ResourceManager.GetString("nb_voi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners.
        /// </summary>
        public static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total prices.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string pro {
            get {
                return ResourceManager.GetString("pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string statitics {
            get {
                return ResourceManager.GetString("statitics", resourceCulture);
            }
        }
    }
}
